export enum WeaponType {
  BareHand = 'Bare Hand',
  Dagger = 'Dagger',
  Bow = 'Bow',
  Instrument = 'Instrument',
  Whip = 'Whip',
  Mace = 'Mace',
  OneHandSword = 'One-Hand Sword',
  TwoHandSword = 'Two-Hand Sword',
  Axe = 'Axe',
  Spear = 'Spear',
  SpearPeco = 'Spear (Peco Peco)',
  Staff = 'Staff',
  Book = 'Book',
  Knuckle = 'Knuckle',
  Katar = 'Katar',
}