import { PropertyElement, ElementLevelTable } from '../../types/propertyElement';

export const level1Table: ElementLevelTable = {
  [PropertyElement.Neutral]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 70,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Water]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 25,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 90,
    [PropertyElement.Wind]: 175,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Earth]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 25,
    [PropertyElement.Fire]: 150,
    [PropertyElement.Wind]: 90,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Fire]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 150,
    [PropertyElement.Earth]: 90,
    [PropertyElement.Fire]: 25,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Wind]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 90,
    [PropertyElement.Earth]: 150,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 25,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Poison]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 50,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 50,
  },

  [PropertyElement.Holy]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 75,
    [PropertyElement.Earth]: 75,
    [PropertyElement.Fire]: 75,
    [PropertyElement.Wind]: 75,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 0,
    [PropertyElement.Shadow]: 125,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Shadow]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 50,
    [PropertyElement.Holy]: 125,
    [PropertyElement.Shadow]: 0,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 0,
  },

  [PropertyElement.Ghost]: {
    [PropertyElement.Neutral]: 70,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 125,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Undead]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 125,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: -25,
    [PropertyElement.Holy]: 150,
    [PropertyElement.Shadow]: -25,
    [PropertyElement.Ghost]: 100,
    [PropertyElement.Undead]: 0,
  },
};