import { PropertyElement, ElementLevelTable } from '../../types/propertyElement';

export const level4Table: ElementLevelTable = {
  [PropertyElement.Neutral]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 0,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Water]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: -50,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 60,
    [PropertyElement.Wind]: 200,
    [PropertyElement.Poison]: 25,
    [PropertyElement.Holy]: 75,
    [PropertyElement.Shadow]: 75,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 25,
  },

  [PropertyElement.Earth]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: -50,
    [PropertyElement.Fire]: 200,
    [PropertyElement.Wind]: 60,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 75,
    [PropertyElement.Shadow]: 75,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 25,
  },

  [PropertyElement.Fire]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 200,
    [PropertyElement.Earth]: 60,
    [PropertyElement.Fire]: -50,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 75,
    [PropertyElement.Shadow]: 75,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 25,
  },

  [PropertyElement.Wind]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 60,
    [PropertyElement.Earth]: 200,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: -50,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 75,
    [PropertyElement.Shadow]: 75,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 25,
  },

  [PropertyElement.Poison]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 75,
    [PropertyElement.Earth]: 75,
    [PropertyElement.Fire]: 75,
    [PropertyElement.Wind]: 75,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: 125,
    [PropertyElement.Shadow]: -25,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: -25,
  },

  [PropertyElement.Holy]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 0,
    [PropertyElement.Earth]: 0,
    [PropertyElement.Fire]: 0,
    [PropertyElement.Wind]: 0,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: -100,
    [PropertyElement.Shadow]: 200,
    [PropertyElement.Ghost]: 0,
    [PropertyElement.Undead]: 175,
  },

  [PropertyElement.Shadow]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 25,
    [PropertyElement.Earth]: 25,
    [PropertyElement.Fire]: 25,
    [PropertyElement.Wind]: 25,
    [PropertyElement.Poison]: -25,
    [PropertyElement.Holy]: 200,
    [PropertyElement.Shadow]: -100,
    [PropertyElement.Ghost]: 0,
    [PropertyElement.Undead]: 0,
  },

  [PropertyElement.Ghost]: {
    [PropertyElement.Neutral]: 0,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 25,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 200,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Undead]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 150,
    [PropertyElement.Earth]: 50,
    [PropertyElement.Fire]: 200,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: -100,
    [PropertyElement.Holy]: 200,
    [PropertyElement.Shadow]: -100,
    [PropertyElement.Ghost]: 175,
    [PropertyElement.Undead]: 0,
  },
};