import { PropertyElement, ElementLevelTable } from '../../types/propertyElement';

export const level2Table: ElementLevelTable = {
  [PropertyElement.Neutral]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Water]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 0,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 80,
    [PropertyElement.Wind]: 175,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 75,
  },

  [PropertyElement.Earth]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 0,
    [PropertyElement.Fire]: 175,
    [PropertyElement.Wind]: 80,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 75,
  },

  [PropertyElement.Fire]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 175,
    [PropertyElement.Earth]: 90,
    [PropertyElement.Fire]: 0,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 75,
  },

  [PropertyElement.Wind]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 80,
    [PropertyElement.Earth]: 175,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 0,
    [PropertyElement.Poison]: 125,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 75,
  },

  [PropertyElement.Poison]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 25,
    [PropertyElement.Ghost]: 75,
    [PropertyElement.Undead]: 25,
  },

  [PropertyElement.Holy]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 50,
    [PropertyElement.Earth]: 50,
    [PropertyElement.Fire]: 50,
    [PropertyElement.Wind]: 50,
    [PropertyElement.Poison]: 50,
    [PropertyElement.Holy]: -25,
    [PropertyElement.Shadow]: 150,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 125,
  },

  [PropertyElement.Shadow]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 75,
    [PropertyElement.Earth]: 75,
    [PropertyElement.Fire]: 75,
    [PropertyElement.Wind]: 75,
    [PropertyElement.Poison]: 25,
    [PropertyElement.Holy]: 150,
    [PropertyElement.Shadow]: -25,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 0,
  },

  [PropertyElement.Ghost]: {
    [PropertyElement.Neutral]: 50,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 75,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 150,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Undead]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 150,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: -50,
    [PropertyElement.Holy]: 175,
    [PropertyElement.Shadow]: -50,
    [PropertyElement.Ghost]: 125,
    [PropertyElement.Undead]: 0,
  },
};