import { PropertyElement, ElementLevelTable } from '../../types/propertyElement';

export const level3Table: ElementLevelTable = {
  [PropertyElement.Neutral]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 0,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Water]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: -25,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 70,
    [PropertyElement.Wind]: 200,
    [PropertyElement.Poison]: 50,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 50,
  },

  [PropertyElement.Earth]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: -25,
    [PropertyElement.Fire]: 200,
    [PropertyElement.Wind]: 70,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 50,
  },

  [PropertyElement.Fire]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 200,
    [PropertyElement.Earth]: 70,
    [PropertyElement.Fire]: -25,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 100,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 50,
  },

  [PropertyElement.Wind]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 70,
    [PropertyElement.Earth]: 200,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: -25,
    [PropertyElement.Poison]: 105,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 50,
  },

  [PropertyElement.Poison]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: 125,
    [PropertyElement.Shadow]: 0,
    [PropertyElement.Ghost]: 50,
    [PropertyElement.Undead]: 0,
  },

  [PropertyElement.Holy]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 25,
    [PropertyElement.Earth]: 25,
    [PropertyElement.Fire]: 25,
    [PropertyElement.Wind]: 25,
    [PropertyElement.Poison]: 25,
    [PropertyElement.Holy]: -50,
    [PropertyElement.Shadow]: 175,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 150,
  },

  [PropertyElement.Shadow]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 50,
    [PropertyElement.Earth]: 50,
    [PropertyElement.Fire]: 50,
    [PropertyElement.Wind]: 50,
    [PropertyElement.Poison]: 0,
    [PropertyElement.Holy]: 175,
    [PropertyElement.Shadow]: -50,
    [PropertyElement.Ghost]: 25,
    [PropertyElement.Undead]: 0,
  },

  [PropertyElement.Ghost]: {
    [PropertyElement.Neutral]: 0,
    [PropertyElement.Water]: 100,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 100,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: 50,
    [PropertyElement.Holy]: 100,
    [PropertyElement.Shadow]: 100,
    [PropertyElement.Ghost]: 175,
    [PropertyElement.Undead]: 100,
  },

  [PropertyElement.Undead]: {
    [PropertyElement.Neutral]: 100,
    [PropertyElement.Water]: 125,
    [PropertyElement.Earth]: 100,
    [PropertyElement.Fire]: 175,
    [PropertyElement.Wind]: 100,
    [PropertyElement.Poison]: -75,
    [PropertyElement.Holy]: 200,
    [PropertyElement.Shadow]: -75,
    [PropertyElement.Ghost]: 150,
    [PropertyElement.Undead]: 0,
  },
};